version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest@sha256:8c909b496d13837354db2855e7fd8563599eb091304bdb7bdbfde0420621fe2f
    steps:
      - checkout
      - run: sudo npm install -g yarn semantic-release@12.0.0
      - run: yarn install
      - run: yarn test
      - run: semantic-release
